import { Schema } from "effect";

export const CostAndUsageRow = Schema.Struct({
  // Mandatory
  BilledCost: Schema.Number,
  BillingAccountId: Schema.String,
  BillingAccountName: Schema.String,
  BillingCurrency: Schema.String,
  BillingPeriodEnd: Schema.String,
  BillingPeriodStart: Schema.String,
  ChargeCategory: Schema.String,
  ChargeClass: Schema.NullOr(Schema.Literal("Correction")),
  ChargeDescription: Schema.String,
  ChargePeriodEnd: Schema.String,
  ChargePeriodStart: Schema.String,
  Provider: Schema.String,
  ServiceCategory: Schema.String,
  ServiceName: Schema.String,
  SubAccountId: Schema.String,
  SubAccountName: Schema.String,

  // Recommended (optional in schema, should be present)
  AvailabilityZone: Schema.optional(Schema.String),
  ChargeFrequency: Schema.optional(Schema.String),
  ContractedCost: Schema.optional(Schema.Number),
  ContractedUnitPrice: Schema.optional(Schema.Number),
  EffectiveCost: Schema.optional(Schema.Number),
  InvoiceId: Schema.optional(Schema.String),
  ListCost: Schema.optional(Schema.Number),
  ListUnitPrice: Schema.optional(Schema.Number),
  PricingCategory: Schema.optional(Schema.String),
  PricingCurrency: Schema.optional(Schema.String),
  PricingCurrencyContractedUnitPrice: Schema.optional(Schema.Number),
  PricingCurrencyEffectiveCost: Schema.optional(Schema.Number),
  PricingCurrencyListUnitPrice: Schema.optional(Schema.Number),
  RegionName: Schema.optional(Schema.String),
  ResourceName: Schema.optional(Schema.String),
  ResourceType: Schema.optional(Schema.String),
  ServiceSubcategory: Schema.optional(Schema.String),
  SkuId: Schema.optional(Schema.String),
  SkuMeter: Schema.optional(Schema.String),
  SkuPriceDetails: Schema.optional(Schema.String),
  SkuPriceId: Schema.optional(Schema.String),
  Tags: Schema.optional(Schema.Record(Schema.String, Schema.String)),

  // Conditional (optional)
  BillingAccountType: Schema.optional(Schema.String),
  CapacityReservationId: Schema.optional(Schema.String),
  CapacityReservationStatus: Schema.optional(Schema.String),
  CommitmentDiscountCategory: Schema.optional(Schema.String),
  CommitmentDiscountId: Schema.optional(Schema.String),
  CommitmentDiscountName: Schema.optional(Schema.String),
  CommitmentDiscountQuantity: Schema.optional(Schema.Number),
  CommitmentDiscountStatus: Schema.optional(Schema.String),
  CommitmentDiscountType: Schema.optional(Schema.String),
  CommitmentDiscountUnit: Schema.optional(Schema.String),
  ConsumedQuantity: Schema.optional(Schema.Number),
  ConsumedUnit: Schema.optional(Schema.String),
  InvoiceIssuer: Schema.optional(Schema.String),
  PricingQuantity: Schema.optional(Schema.Number),
  PricingUnit: Schema.optional(Schema.String),
  Publisher: Schema.optional(Schema.String),
  RegionId: Schema.optional(Schema.String),
  ResourceId: Schema.optional(Schema.String),
  SubAccountType: Schema.optional(Schema.String),
});

export type CostAndUsageRow = typeof CostAndUsageRow.Type;
