export type FocusColumn = {
  name: string;
  displayName: string;
  introducedVersion: string;
  category: string;
  dataType: "String" | "Decimal" | "DateTime" | "KeyValue" | "JSON";
  status: "Mandatory" | "Conditional" | "Recommended" | "Optional";
  description: string;
  deprecated?: boolean;
};

export const costAndUsageColumns: FocusColumn[] = [
  {
    name: "AllocatedMethodDetails",
    displayName: "Allocated Method Details",
    introducedVersion: "1.3",
    category: "Allocation",
    dataType: "JSON",
    status: "Recommended",
    description:
      "A set of properties describing how resources are allocated in data generator-defined split cost allocation.",
  },
  {
    name: "AllocatedMethodId",
    displayName: "Allocated Method ID",
    introducedVersion: "1.3",
    category: "Allocation",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the allocation method used to split costs.",
  },
  {
    name: "AllocatedResourceId",
    displayName: "Allocated Resource ID",
    introducedVersion: "1.3",
    category: "Allocation",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the resource the cost was allocated to.",
  },
  {
    name: "AllocatedResourceName",
    displayName: "Allocated Resource Name",
    introducedVersion: "1.3",
    category: "Allocation",
    dataType: "String",
    status: "Conditional",
    description: "The name of the resource the cost was allocated to.",
  },
  {
    name: "AllocatedTags",
    displayName: "Allocated Tags",
    introducedVersion: "1.3",
    category: "Allocation",
    dataType: "JSON",
    status: "Conditional",
    description:
      "A set of tags assigned to tag sources that are applicable to allocated charges in data generator-calculated split cost allocation.",
  },
  {
    name: "AvailabilityZone",
    displayName: "Availability Zone",
    introducedVersion: "0.5",
    category: "Location",
    dataType: "String",
    status: "Recommended",
    description: "The availability zone in which a resource is running or a service is provided.",
  },
  {
    name: "BilledCost",
    displayName: "Billed Cost",
    introducedVersion: "0.5",
    category: "Billing",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The amount charged to the buyer, net of any discounts applied, after any applicable credits.",
  },
  {
    name: "BillingAccountId",
    displayName: "Billing Account ID",
    introducedVersion: "0.5",
    category: "Account",
    dataType: "String",
    status: "Mandatory",
    description: "The identifier of the billing account responsible for the costs.",
  },
  {
    name: "BillingAccountName",
    displayName: "Billing Account Name",
    introducedVersion: "0.5",
    category: "Account",
    dataType: "String",
    status: "Mandatory",
    description: "The name of the billing account responsible for the costs.",
  },
  {
    name: "BillingAccountType",
    displayName: "Billing Account Type",
    introducedVersion: "1.2",
    category: "Account",
    dataType: "String",
    status: "Conditional",
    description: "The type of the billing account responsible for the costs.",
  },
  {
    name: "BillingCurrency",
    displayName: "Billing Currency",
    introducedVersion: "0.5",
    category: "Billing",
    dataType: "String",
    status: "Mandatory",
    description: "The currency used for the billing of the cost.",
  },
  {
    name: "BillingPeriodEnd",
    displayName: "Billing Period End",
    introducedVersion: "0.5",
    category: "Timeframe",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The end date and time of the billing period.",
  },
  {
    name: "BillingPeriodStart",
    displayName: "Billing Period Start",
    introducedVersion: "0.5",
    category: "Timeframe",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The start date and time of the billing period.",
  },
  {
    name: "CapacityReservationId",
    displayName: "Capacity Reservation ID",
    introducedVersion: "1.1",
    category: "Capacity Reservation",
    dataType: "String",
    status: "Conditional",
    description: "The identifier assigned to a capacity reservation by the provider.",
  },
  {
    name: "CapacityReservationStatus",
    displayName: "Capacity Reservation Status",
    introducedVersion: "1.1",
    category: "Capacity Reservation",
    dataType: "String",
    status: "Conditional",
    description: "Indicates whether a charge represents consumption or the unused portion of a capacity reservation.",
  },
  {
    name: "ChargeCategory",
    displayName: "Charge Category",
    introducedVersion: "0.5",
    category: "Charge",
    dataType: "String",
    status: "Mandatory",
    description: "The category of the charge. Allowed values: Usage, Purchase, Tax, Credit, Adjustment.",
  },
  {
    name: "ChargeClass",
    displayName: "Charge Class",
    introducedVersion: "1.0",
    category: "Charge",
    dataType: "String",
    status: "Mandatory",
    description: "Indicates whether the row represents a correction to a previously invoiced billing period.",
  },
  {
    name: "ChargeDescription",
    displayName: "Charge Description",
    introducedVersion: "1.0",
    category: "Charge",
    dataType: "String",
    status: "Mandatory",
    description: "A description of the charge.",
  },
  {
    name: "ChargeFrequency",
    displayName: "Charge Frequency",
    introducedVersion: "1.0",
    category: "Charge",
    dataType: "String",
    status: "Recommended",
    description: "The frequency of the charge. Allowed values: One-Time, Recurring, Usage-Based.",
  },
  {
    name: "ChargePeriodEnd",
    displayName: "Charge Period End",
    introducedVersion: "0.5",
    category: "Timeframe",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The end date and time of the charge period.",
  },
  {
    name: "ChargePeriodStart",
    displayName: "Charge Period Start",
    introducedVersion: "0.5",
    category: "Timeframe",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The start date and time of the charge period.",
  },
  {
    name: "CommitmentDiscountCategory",
    displayName: "Commitment Discount Category",
    introducedVersion: "1.0",
    category: "Commitment Discount",
    dataType: "String",
    status: "Conditional",
    description: "The category of commitment discount applied. Allowed values: Spend, Usage.",
  },
  {
    name: "CommitmentDiscountId",
    displayName: "Commitment Discount ID",
    introducedVersion: "1.0",
    category: "Commitment Discount",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the commitment discount applied.",
  },
  {
    name: "CommitmentDiscountName",
    displayName: "Commitment Discount Name",
    introducedVersion: "1.0",
    category: "Commitment Discount",
    dataType: "String",
    status: "Conditional",
    description: "The name of the commitment discount applied.",
  },
  {
    name: "CommitmentDiscountQuantity",
    displayName: "Commitment Discount Quantity",
    introducedVersion: "1.1",
    category: "Commitment Discount",
    dataType: "Decimal",
    status: "Conditional",
    description: "The amount of a commitment discount purchased or accounted for in a given row.",
  },
  {
    name: "CommitmentDiscountStatus",
    displayName: "Commitment Discount Status",
    introducedVersion: "1.0",
    category: "Commitment Discount",
    dataType: "String",
    status: "Conditional",
    description:
      "Indicates whether the charge corresponds to the used or unused portion of a commitment discount. Allowed values: Used, Unused.",
  },
  {
    name: "CommitmentDiscountType",
    displayName: "Commitment Discount Type",
    introducedVersion: "1.0",
    category: "Commitment Discount",
    dataType: "String",
    status: "Conditional",
    description: "The type of commitment discount applied.",
  },
  {
    name: "CommitmentDiscountUnit",
    displayName: "Commitment Discount Unit",
    introducedVersion: "1.1",
    category: "Commitment Discount",
    dataType: "String",
    status: "Conditional",
    description:
      "The provider-specified measurement unit indicating how a provider measures the CommitmentDiscountQuantity.",
  },
  {
    name: "ConsumedQuantity",
    displayName: "Consumed Quantity",
    introducedVersion: "1.0",
    category: "Billing",
    dataType: "Decimal",
    status: "Conditional",
    description: "The quantity of a resource or service consumed.",
  },
  {
    name: "ConsumedUnit",
    displayName: "Consumed Unit",
    introducedVersion: "1.0",
    category: "Billing",
    dataType: "String",
    status: "Conditional",
    description: "The unit of measure for the consumed quantity.",
  },
  {
    name: "ContractApplied",
    displayName: "Contract Applied",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "JSON",
    status: "Conditional",
    description: "A set of properties that associate a charge with one or more contract commitments.",
  },
  {
    name: "ContractedCost",
    displayName: "Contracted Cost",
    introducedVersion: "1.0",
    category: "Billing",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The cost calculated by multiplying contracted unit price by the pricing quantity.",
  },
  {
    name: "ContractedUnitPrice",
    displayName: "Contracted Unit Price",
    introducedVersion: "1.0",
    category: "Billing",
    dataType: "Decimal",
    status: "Conditional",
    description: "The contracted unit price for the pricing unit.",
  },
  {
    name: "EffectiveCost",
    displayName: "Effective Cost",
    introducedVersion: "0.5",
    category: "Billing",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The amortized cost inclusive of the impact of commitment-based discounts.",
  },
  {
    name: "HostProviderName",
    displayName: "Host Provider Name",
    introducedVersion: "1.3",
    category: "Charge Origination",
    dataType: "String",
    status: "Mandatory",
    description: "The name of the provider hosting the resource or service.",
  },
  {
    name: "InvoiceId",
    displayName: "Invoice ID",
    introducedVersion: "1.2",
    category: "Charge Origination",
    dataType: "String",
    status: "Recommended",
    description: "The identifier of the invoice associated with the charge.",
  },
  {
    name: "InvoiceIssuerName",
    displayName: "Invoice Issuer Name",
    introducedVersion: "0.5",
    category: "Charge Origination",
    dataType: "String",
    status: "Mandatory",
    description: "The name of the entity responsible for invoicing the customer.",
  },
  {
    name: "ListCost",
    displayName: "List Cost",
    introducedVersion: "1.0",
    category: "Billing",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The cost calculated by multiplying the list unit price by the pricing quantity.",
  },
  {
    name: "ListUnitPrice",
    displayName: "List Unit Price",
    introducedVersion: "1.0",
    category: "Billing",
    dataType: "Decimal",
    status: "Conditional",
    description: "The list unit price for the pricing unit, before any discounts.",
  },
  {
    name: "PricingCategory",
    displayName: "Pricing Category",
    introducedVersion: "1.0",
    category: "Pricing",
    dataType: "String",
    status: "Conditional",
    description: "The pricing model used. Allowed values: Standard, Dynamic, Committed, Other.",
  },
  {
    name: "PricingCurrency",
    displayName: "Pricing Currency",
    introducedVersion: "1.2",
    category: "Pricing",
    dataType: "String",
    status: "Conditional",
    description: "The currency used for pricing prior to conversion to the billing currency.",
  },
  {
    name: "PricingCurrencyContractedUnitPrice",
    displayName: "Pricing Currency Contracted Unit Price",
    introducedVersion: "1.2",
    category: "Pricing",
    dataType: "Decimal",
    status: "Conditional",
    description: "The contracted unit price expressed in the pricing currency.",
  },
  {
    name: "PricingCurrencyEffectiveCost",
    displayName: "Pricing Currency Effective Cost",
    introducedVersion: "1.2",
    category: "Pricing",
    dataType: "Decimal",
    status: "Conditional",
    description: "The effective cost expressed in the pricing currency.",
  },
  {
    name: "PricingCurrencyListUnitPrice",
    displayName: "Pricing Currency List Unit Price",
    introducedVersion: "1.2",
    category: "Pricing",
    dataType: "Decimal",
    status: "Conditional",
    description: "The list unit price expressed in the pricing currency.",
  },
  {
    name: "PricingQuantity",
    displayName: "Pricing Quantity",
    introducedVersion: "1.0",
    category: "Pricing",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The quantity used for pricing calculations.",
  },
  {
    name: "PricingUnit",
    displayName: "Pricing Unit",
    introducedVersion: "1.0",
    category: "Pricing",
    dataType: "String",
    status: "Mandatory",
    description: "Service-provider-specified measurement unit for determining unit prices.",
  },
  {
    name: "ProviderName",
    displayName: "Provider",
    introducedVersion: "0.5",
    category: "Charge Origination",
    dataType: "String",
    status: "Mandatory",
    description:
      "The name of the entity that made the resources or services available for purchase. Deprecated in 1.3 — use ServiceProviderName instead.",
    deprecated: true,
  },
  {
    name: "PublisherName",
    displayName: "Publisher",
    introducedVersion: "0.5",
    category: "Charge Origination",
    dataType: "String",
    status: "Mandatory",
    description:
      "The name of the entity that produced the resources or services that were purchased. Deprecated in 1.3.",
    deprecated: true,
  },
  {
    name: "RegionId",
    displayName: "Region ID",
    introducedVersion: "0.5",
    category: "Location",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the geographic area where the resource is located.",
  },
  {
    name: "RegionName",
    displayName: "Region Name",
    introducedVersion: "1.0",
    category: "Location",
    dataType: "String",
    status: "Conditional",
    description: "The name of the geographic area where the resource is located.",
  },
  {
    name: "ResourceId",
    displayName: "Resource ID",
    introducedVersion: "0.5",
    category: "Resource",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the resource.",
  },
  {
    name: "ResourceName",
    displayName: "Resource Name",
    introducedVersion: "0.5",
    category: "Resource",
    dataType: "String",
    status: "Conditional",
    description: "The name of the resource.",
  },
  {
    name: "ResourceType",
    displayName: "Resource Type",
    introducedVersion: "1.0",
    category: "Resource",
    dataType: "String",
    status: "Conditional",
    description: "The type or category of the resource.",
  },
  {
    name: "ServiceCategory",
    displayName: "Service Category",
    introducedVersion: "0.5",
    category: "Service",
    dataType: "String",
    status: "Mandatory",
    description: "The highest-level classification of a service based on its core function.",
  },
  {
    name: "ServiceName",
    displayName: "Service Name",
    introducedVersion: "0.5",
    category: "Service",
    dataType: "String",
    status: "Mandatory",
    description: "An offering that can be purchased from a provider.",
  },
  {
    name: "ServiceProviderName",
    displayName: "Service Provider Name",
    introducedVersion: "1.3",
    category: "Charge Origination",
    dataType: "String",
    status: "Mandatory",
    description:
      "The name of the entity that made the resources or services available for purchase. Replaces deprecated ProviderName.",
  },
  {
    name: "ServiceSubcategory",
    displayName: "Service Subcategory",
    introducedVersion: "1.1",
    category: "Service",
    dataType: "String",
    status: "Recommended",
    description: "A secondary classification of a service that provides additional detail within a ServiceCategory.",
  },
  {
    name: "SkuId",
    displayName: "SKU ID",
    introducedVersion: "1.0",
    category: "SKU",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the cloud product in the provider's catalog.",
  },
  {
    name: "SkuMeter",
    displayName: "SKU Meter",
    introducedVersion: "1.1",
    category: "SKU",
    dataType: "String",
    status: "Conditional",
    description: "The name of the measurement type used to identify the unit of measure for a specific SKU resource.",
  },
  {
    name: "SkuPriceDetails",
    displayName: "SKU Price Details",
    introducedVersion: "1.1",
    category: "SKU",
    dataType: "JSON",
    status: "Conditional",
    description:
      "A set of properties of a SKU Price ID which are meaningful and common to all instances of that SKU Price ID.",
  },
  {
    name: "SkuPriceId",
    displayName: "SKU Price ID",
    introducedVersion: "1.0",
    category: "SKU",
    dataType: "String",
    status: "Conditional",
    description: "The identifier for the price of a given SKU.",
  },
  {
    name: "SubAccountId",
    displayName: "Sub Account ID",
    introducedVersion: "0.5",
    category: "Account",
    dataType: "String",
    status: "Conditional",
    description: "An ID assigned to a grouping of resources or services, often used to manage access and/or cost.",
  },
  {
    name: "SubAccountName",
    displayName: "Sub Account Name",
    introducedVersion: "0.5",
    category: "Account",
    dataType: "String",
    status: "Conditional",
    description: "The name of the sub-account or project responsible for the costs.",
  },
  {
    name: "SubAccountType",
    displayName: "Sub Account Type",
    introducedVersion: "1.2",
    category: "Account",
    dataType: "String",
    status: "Conditional",
    description: "The type of the sub-account or project responsible for the costs.",
  },
  {
    name: "Tags",
    displayName: "Tags",
    introducedVersion: "1.0",
    category: "Resource",
    dataType: "JSON",
    status: "Conditional",
    description:
      "The set of tags assigned to tag sources that account for potential provider-defined or user-defined tag evaluations.",
  },
];

export const contractCommitmentColumns: FocusColumn[] = [
  {
    name: "BillingCurrency",
    displayName: "Billing Currency",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "String",
    status: "Mandatory",
    description: "The currency used for the billing of the contract commitment.",
  },
  {
    name: "ContractCommitmentCategory",
    displayName: "Contract Commitment Category",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "String",
    status: "Mandatory",
    description: "The category of the contract commitment. Allowed values: Spend, Usage.",
  },
  {
    name: "ContractCommitmentCost",
    displayName: "Contract Commitment Cost",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The cost associated with the contract commitment.",
  },
  {
    name: "ContractCommitmentDescription",
    displayName: "Contract Commitment Description",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "String",
    status: "Mandatory",
    description: "A description of the contract commitment.",
  },
  {
    name: "ContractCommitmentId",
    displayName: "Contract Commitment ID",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "String",
    status: "Mandatory",
    description: "The identifier of the contract commitment.",
  },
  {
    name: "ContractCommitmentPeriodEnd",
    displayName: "Contract Commitment Period End",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The end date and time of the contract commitment period.",
  },
  {
    name: "ContractCommitmentPeriodStart",
    displayName: "Contract Commitment Period Start",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The start date and time of the contract commitment period.",
  },
  {
    name: "ContractCommitmentQuantity",
    displayName: "Contract Commitment Quantity",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The quantity associated with the contract commitment.",
  },
  {
    name: "ContractCommitmentType",
    displayName: "Contract Commitment Type",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "String",
    status: "Mandatory",
    description: "The type of the contract commitment.",
  },
  {
    name: "ContractCommitmentUnit",
    displayName: "Contract Commitment Unit",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "String",
    status: "Mandatory",
    description: "The unit of measure for the contract commitment quantity.",
  },
  {
    name: "ContractId",
    displayName: "Contract ID",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "String",
    status: "Mandatory",
    description: "The identifier of the contract associated with the commitment.",
  },
  {
    name: "ContractPeriodEnd",
    displayName: "Contract Period End",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The end date and time of the contract period.",
  },
  {
    name: "ContractPeriodStart",
    displayName: "Contract Period Start",
    introducedVersion: "1.3",
    category: "Contract",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The start date and time of the contract period.",
  },
];
