export type FocusColumn = {
  name: string;
  displayName: string;
  introducedVersion: string;
  category: string;
  columnType: "Dimension" | "Metric";
  dataType: "String" | "Decimal" | "DateTime" | "KeyValue";
  status: "Mandatory" | "Conditional" | "Recommended" | "Optional";
  description: string;
};

export const columns: FocusColumn[] = [
  {
    name: "AvailabilityZone",
    displayName: "Availability Zone",
    introducedVersion: "0.5",
    category: "Location",
    columnType: "Dimension",
    dataType: "String",
    status: "Recommended",
    description: "The availability zone in which a resource is running or a service is provided.",
  },
  {
    name: "BilledCost",
    displayName: "Billed Cost",
    introducedVersion: "0.5",
    category: "Billing",
    columnType: "Metric",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The amount charged to the buyer, net of any discounts applied, after any applicable credits.",
  },
  {
    name: "BillingAccountId",
    displayName: "Billing Account ID",
    introducedVersion: "0.5",
    category: "Account",
    columnType: "Dimension",
    dataType: "String",
    status: "Mandatory",
    description: "The identifier of the billing account responsible for the costs.",
  },
  {
    name: "BillingAccountName",
    displayName: "Billing Account Name",
    introducedVersion: "0.5",
    category: "Account",
    columnType: "Dimension",
    dataType: "String",
    status: "Mandatory",
    description: "The name of the billing account responsible for the costs.",
  },
  {
    name: "BillingCurrency",
    displayName: "Billing Currency",
    introducedVersion: "0.5",
    category: "Billing",
    columnType: "Dimension",
    dataType: "String",
    status: "Mandatory",
    description: "The currency used for the billing of the cost.",
  },
  {
    name: "BillingPeriodEnd",
    displayName: "Billing Period End",
    introducedVersion: "0.5",
    category: "Timeframe",
    columnType: "Dimension",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The end date and time of the billing period.",
  },
  {
    name: "BillingPeriodStart",
    displayName: "Billing Period Start",
    introducedVersion: "0.5",
    category: "Timeframe",
    columnType: "Dimension",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The start date and time of the billing period.",
  },
  {
    name: "CapacityReservationId",
    displayName: "Capacity Reservation ID",
    introducedVersion: "1.1",
    category: "Capacity Reservation",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The identifier assigned to a capacity reservation by the provider.",
  },
  {
    name: "CapacityReservationStatus",
    displayName: "Capacity Reservation Status",
    introducedVersion: "1.1",
    category: "Capacity Reservation",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "Indicates whether a charge represents consumption or the unused portion of a capacity reservation.",
  },
  {
    name: "ChargeCategory",
    displayName: "Charge Category",
    introducedVersion: "0.5",
    category: "Charge",
    columnType: "Dimension",
    dataType: "String",
    status: "Mandatory",
    description: "The category of the charge (e.g., Usage, Purchase, Tax, Credit, Adjustment).",
  },
  {
    name: "ChargeClass",
    displayName: "Charge Class",
    introducedVersion: "1.0",
    category: "Charge",
    columnType: "Dimension",
    dataType: "String",
    status: "Mandatory",
    description: 'Null for regular charges; "Correction" when the row corrects a prior-period charge.',
  },
  {
    name: "ChargeDescription",
    displayName: "Charge Description",
    introducedVersion: "1.0",
    category: "Charge",
    columnType: "Dimension",
    dataType: "String",
    status: "Mandatory",
    description: "A description of the charge.",
  },
  {
    name: "ChargeFrequency",
    displayName: "Charge Frequency",
    introducedVersion: "1.0",
    category: "Charge",
    columnType: "Dimension",
    dataType: "String",
    status: "Recommended",
    description: "The frequency of the charge (e.g., One-Time, Recurring, Usage-Based).",
  },
  {
    name: "ChargePeriodEnd",
    displayName: "Charge Period End",
    introducedVersion: "0.5",
    category: "Timeframe",
    columnType: "Dimension",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The end date and time of the charge period.",
  },
  {
    name: "ChargePeriodStart",
    displayName: "Charge Period Start",
    introducedVersion: "0.5",
    category: "Timeframe",
    columnType: "Dimension",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The start date and time of the charge period.",
  },
  {
    name: "CommitmentDiscountCategory",
    displayName: "Commitment Discount Category",
    introducedVersion: "1.0",
    category: "Commitment Discount",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The category of commitment discount applied (e.g., Spend, Usage).",
  },
  {
    name: "CommitmentDiscountId",
    displayName: "Commitment Discount ID",
    introducedVersion: "1.0",
    category: "Commitment Discount",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the commitment discount applied.",
  },
  {
    name: "CommitmentDiscountName",
    displayName: "Commitment Discount Name",
    introducedVersion: "1.0",
    category: "Commitment Discount",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The name of the commitment discount applied.",
  },
  {
    name: "CommitmentDiscountQuantity",
    displayName: "Commitment Discount Quantity",
    introducedVersion: "1.1",
    category: "Commitment Discount",
    columnType: "Metric",
    dataType: "Decimal",
    status: "Conditional",
    description: "The amount of a commitment discount purchased or accounted for in a given row.",
  },
  {
    name: "CommitmentDiscountStatus",
    displayName: "Commitment Discount Status",
    introducedVersion: "1.0",
    category: "Commitment Discount",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The status of the commitment discount (e.g., Used, Unused).",
  },
  {
    name: "CommitmentDiscountType",
    displayName: "Commitment Discount Type",
    introducedVersion: "1.0",
    category: "Commitment Discount",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The type of commitment discount (e.g., Reserved, Savings Plan).",
  },
  {
    name: "CommitmentDiscountUnit",
    displayName: "Commitment Discount Unit",
    introducedVersion: "1.1",
    category: "Commitment Discount",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description:
      "The provider-specified measurement unit indicating how a provider measures the CommitmentDiscountQuantity.",
  },
  {
    name: "ConsumedQuantity",
    displayName: "Consumed Quantity",
    introducedVersion: "1.0",
    category: "Billing",
    columnType: "Metric",
    dataType: "Decimal",
    status: "Conditional",
    description: "The quantity of a resource or service consumed.",
  },
  {
    name: "ConsumedUnit",
    displayName: "Consumed Unit",
    introducedVersion: "1.0",
    category: "Billing",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The unit of measure for the consumed quantity.",
  },
  {
    name: "ContractedCost",
    displayName: "Contracted Cost",
    introducedVersion: "1.0",
    category: "Billing",
    columnType: "Metric",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The cost calculated by multiplying contracted unit price by the pricing quantity.",
  },
  {
    name: "ContractedUnitPrice",
    displayName: "Contracted Unit Price",
    introducedVersion: "1.0",
    category: "Billing",
    columnType: "Metric",
    dataType: "Decimal",
    status: "Conditional",
    description: "The contracted unit price for the pricing unit.",
  },
  {
    name: "EffectiveCost",
    displayName: "Effective Cost",
    introducedVersion: "0.5",
    category: "Billing",
    columnType: "Metric",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The amortized cost inclusive of the impact of commitment-based discounts.",
  },
  {
    name: "InvoiceIssuerName",
    displayName: "Invoice Issuer Name",
    introducedVersion: "0.5",
    category: "Charge Origination",
    columnType: "Dimension",
    dataType: "String",
    status: "Mandatory",
    description: "The name of the entity responsible for invoicing the customer.",
  },
  {
    name: "ListCost",
    displayName: "List Cost",
    introducedVersion: "1.0",
    category: "Billing",
    columnType: "Metric",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The cost calculated by multiplying the list unit price by the pricing quantity.",
  },
  {
    name: "ListUnitPrice",
    displayName: "List Unit Price",
    introducedVersion: "1.0",
    category: "Billing",
    columnType: "Metric",
    dataType: "Decimal",
    status: "Conditional",
    description: "The list unit price for the pricing unit, before any discounts.",
  },
  {
    name: "PricingCategory",
    displayName: "Pricing Category",
    introducedVersion: "1.0",
    category: "Pricing",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The pricing model used (e.g., Standard, Dynamic, Committed).",
  },
  {
    name: "PricingQuantity",
    displayName: "Pricing Quantity",
    introducedVersion: "1.0",
    category: "Pricing",
    columnType: "Metric",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The quantity used for pricing calculations.",
  },
  {
    name: "PricingUnit",
    displayName: "Pricing Unit",
    introducedVersion: "1.0",
    category: "Pricing",
    columnType: "Dimension",
    dataType: "String",
    status: "Mandatory",
    description: "The unit of measure used for pricing calculations.",
  },
  {
    name: "ProviderName",
    displayName: "Provider",
    introducedVersion: "0.5",
    category: "Charge Origination",
    columnType: "Dimension",
    dataType: "String",
    status: "Mandatory",
    description: "The name of the entity that made the resources or services available for purchase.",
  },
  {
    name: "PublisherName",
    displayName: "Publisher",
    introducedVersion: "0.5",
    category: "Charge Origination",
    columnType: "Dimension",
    dataType: "String",
    status: "Mandatory",
    description: "The name of the entity that provides the resources or services.",
  },
  {
    name: "RegionId",
    displayName: "Region ID",
    introducedVersion: "0.5",
    category: "Location",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the geographic area where the resource is located.",
  },
  {
    name: "RegionName",
    displayName: "Region Name",
    introducedVersion: "1.0",
    category: "Location",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The name of the geographic area where the resource is located.",
  },
  {
    name: "ResourceId",
    displayName: "Resource ID",
    introducedVersion: "0.5",
    category: "Resource",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the resource.",
  },
  {
    name: "ResourceName",
    displayName: "Resource Name",
    introducedVersion: "0.5",
    category: "Resource",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The name of the resource.",
  },
  {
    name: "ResourceType",
    displayName: "Resource Type",
    introducedVersion: "1.0",
    category: "Resource",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The type or category of the resource.",
  },
  {
    name: "ServiceCategory",
    displayName: "Service Category",
    introducedVersion: "0.5",
    category: "Service",
    columnType: "Dimension",
    dataType: "String",
    status: "Mandatory",
    description: "The highest-level classification of a service based on its core function.",
  },
  {
    name: "ServiceName",
    displayName: "Service Name",
    introducedVersion: "0.5",
    category: "Service",
    columnType: "Dimension",
    dataType: "String",
    status: "Mandatory",
    description: "An offering that can be purchased from a provider.",
  },
  {
    name: "ServiceSubcategory",
    displayName: "Service Subcategory",
    introducedVersion: "1.1",
    category: "Service",
    columnType: "Dimension",
    dataType: "String",
    status: "Recommended",
    description: "A secondary classification of a service that provides additional detail within a ServiceCategory.",
  },
  {
    name: "SkuId",
    displayName: "SKU ID",
    introducedVersion: "1.0",
    category: "SKU",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the cloud product in the provider's catalog.",
  },
  {
    name: "SkuMeter",
    displayName: "SKU Meter",
    introducedVersion: "1.1",
    category: "SKU",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The name of the measurement type used to identify the unit of measure for a specific SKU resource.",
  },
  {
    name: "SkuPriceDetails",
    displayName: "SKU Price Details",
    introducedVersion: "1.1",
    category: "SKU",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "Additional pricing details for the given SKU price.",
  },
  {
    name: "SkuPriceId",
    displayName: "SKU Price ID",
    introducedVersion: "1.0",
    category: "SKU",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The identifier for the price of a given SKU.",
  },
  {
    name: "SubAccountId",
    displayName: "Sub Account ID",
    introducedVersion: "0.5",
    category: "Account",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the sub-account or project responsible for the costs.",
  },
  {
    name: "SubAccountName",
    displayName: "Sub Account Name",
    introducedVersion: "0.5",
    category: "Account",
    columnType: "Dimension",
    dataType: "String",
    status: "Conditional",
    description: "The name of the sub-account or project responsible for the costs.",
  },
  {
    name: "Tags",
    displayName: "Tags",
    introducedVersion: "1.0",
    category: "Resource",
    columnType: "Dimension",
    dataType: "KeyValue",
    status: "Conditional",
    description: "A set of key-value pairs applied to the resource or service.",
  },
];
