export type FocusColumn = {
  name: string;
  dataType: "String" | "Decimal" | "DateTime" | "KeyValue";
  status: "Mandatory" | "Conditional" | "Recommended" | "Optional";
  description: string;
};

export const columns: FocusColumn[] = [
  {
    name: "AvailabilityZone",
    dataType: "String",
    status: "Recommended",
    description: "The availability zone in which a resource is running or a service is provided.",
  },
  {
    name: "BilledCost",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The amount charged to the buyer, net of any discounts applied, after any applicable credits.",
  },
  {
    name: "BillingAccountId",
    dataType: "String",
    status: "Mandatory",
    description: "The identifier of the billing account responsible for the costs.",
  },
  {
    name: "BillingAccountName",
    dataType: "String",
    status: "Mandatory",
    description: "The name of the billing account responsible for the costs.",
  },
  {
    name: "BillingCurrency",
    dataType: "String",
    status: "Mandatory",
    description: "The currency used for the billing of the cost.",
  },
  {
    name: "BillingPeriodEnd",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The end date and time of the billing period.",
  },
  {
    name: "BillingPeriodStart",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The start date and time of the billing period.",
  },
  {
    name: "ChargeCategory",
    dataType: "String",
    status: "Mandatory",
    description: "The category of the charge (e.g., Usage, Purchase, Tax, Credit, Adjustment).",
  },
  {
    name: "ChargeClass",
    dataType: "String",
    status: "Mandatory",
    description: 'Null for regular charges; "Correction" when the row corrects a prior-period charge.',
  },
  {
    name: "ChargeDescription",
    dataType: "String",
    status: "Mandatory",
    description: "A description of the charge.",
  },
  {
    name: "ChargeFrequency",
    dataType: "String",
    status: "Recommended",
    description: "The frequency of the charge (e.g., One-Time, Recurring, Usage-Based).",
  },
  {
    name: "ChargePeriodEnd",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The end date and time of the charge period.",
  },
  {
    name: "ChargePeriodStart",
    dataType: "DateTime",
    status: "Mandatory",
    description: "The start date and time of the charge period.",
  },
  {
    name: "CommitmentDiscountCategory",
    dataType: "String",
    status: "Conditional",
    description: "The category of commitment discount applied (e.g., Spend, Usage).",
  },
  {
    name: "CommitmentDiscountId",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the commitment discount applied.",
  },
  {
    name: "CommitmentDiscountName",
    dataType: "String",
    status: "Conditional",
    description: "The name of the commitment discount applied.",
  },
  {
    name: "CommitmentDiscountStatus",
    dataType: "String",
    status: "Conditional",
    description: "The status of the commitment discount (e.g., Used, Unused).",
  },
  {
    name: "CommitmentDiscountType",
    dataType: "String",
    status: "Conditional",
    description: "The type of commitment discount (e.g., Reserved, Savings Plan).",
  },
  {
    name: "ConsumedQuantity",
    dataType: "Decimal",
    status: "Conditional",
    description: "The quantity of a resource or service consumed.",
  },
  {
    name: "ConsumedUnit",
    dataType: "String",
    status: "Conditional",
    description: "The unit of measure for the consumed quantity.",
  },
  {
    name: "ContractedCost",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The cost calculated by multiplying contracted unit price by the pricing quantity.",
  },
  {
    name: "ContractedUnitPrice",
    dataType: "Decimal",
    status: "Conditional",
    description: "The contracted unit price for the pricing unit.",
  },
  {
    name: "EffectiveCost",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The amortized cost inclusive of the impact of commitment-based discounts.",
  },
  {
    name: "InvoiceIssuerName",
    dataType: "String",
    status: "Mandatory",
    description: "The name of the entity responsible for invoicing the customer.",
  },
  {
    name: "ListCost",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The cost calculated by multiplying the list unit price by the pricing quantity.",
  },
  {
    name: "ListUnitPrice",
    dataType: "Decimal",
    status: "Conditional",
    description: "The list unit price for the pricing unit, before any discounts.",
  },
  {
    name: "PricingCategory",
    dataType: "String",
    status: "Conditional",
    description: "The pricing model used (e.g., Standard, Dynamic, Committed).",
  },
  {
    name: "PricingQuantity",
    dataType: "Decimal",
    status: "Mandatory",
    description: "The quantity used for pricing calculations.",
  },
  {
    name: "PricingUnit",
    dataType: "String",
    status: "Mandatory",
    description: "The unit of measure used for pricing calculations.",
  },
  {
    name: "ProviderName",
    dataType: "String",
    status: "Mandatory",
    description: "The name of the entity that made the resources or services available for purchase.",
  },
  {
    name: "PublisherName",
    dataType: "String",
    status: "Mandatory",
    description: "The name of the entity that provides the resources or services.",
  },
  {
    name: "RegionId",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the geographic area where the resource is located.",
  },
  {
    name: "RegionName",
    dataType: "String",
    status: "Conditional",
    description: "The name of the geographic area where the resource is located.",
  },
  {
    name: "ResourceId",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the resource.",
  },
  {
    name: "ResourceName",
    dataType: "String",
    status: "Conditional",
    description: "The name of the resource.",
  },
  {
    name: "ResourceType",
    dataType: "String",
    status: "Conditional",
    description: "The type or category of the resource.",
  },
  {
    name: "ServiceCategory",
    dataType: "String",
    status: "Mandatory",
    description: "The highest-level classification of a service based on its core function.",
  },
  {
    name: "ServiceName",
    dataType: "String",
    status: "Mandatory",
    description: "An offering that can be purchased from a provider.",
  },
  {
    name: "SkuId",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the cloud product in the provider's catalog.",
  },
  {
    name: "SkuPriceId",
    dataType: "String",
    status: "Conditional",
    description: "The identifier for the price of a given SKU.",
  },
  {
    name: "SubAccountId",
    dataType: "String",
    status: "Conditional",
    description: "The identifier of the sub-account or project responsible for the costs.",
  },
  {
    name: "SubAccountName",
    dataType: "String",
    status: "Conditional",
    description: "The name of the sub-account or project responsible for the costs.",
  },
  {
    name: "Tags",
    dataType: "KeyValue",
    status: "Conditional",
    description: "A set of key-value pairs applied to the resource or service.",
  },
];
