import { Schema } from "effect";

export const CostAndUsageRow = Schema.Struct({
  // Mandatory fields
  BilledCost: Schema.Number,
  BillingAccountId: Schema.String,
  BillingAccountName: Schema.NullOr(Schema.String),
  BillingCurrency: Schema.String,
  BillingPeriodEnd: Schema.String,
  BillingPeriodStart: Schema.String,
  ChargeCategory: Schema.Literals(["Usage", "Purchase", "Tax", "Credit", "Adjustment"]),
  ChargeClass: Schema.NullOr(Schema.Literal("Correction")),
  ChargeDescription: Schema.NullOr(Schema.String),
  ChargePeriodEnd: Schema.String,
  ChargePeriodStart: Schema.String,
  ContractedCost: Schema.Number,
  EffectiveCost: Schema.Number,
  InvoiceIssuer: Schema.String,
  ListCost: Schema.Number,
  PricingQuantity: Schema.NullOr(Schema.Number),
  PricingUnit: Schema.NullOr(Schema.String),
  Provider: Schema.String,
  Publisher: Schema.String,
  ServiceCategory: Schema.Literals([
    "AI and Machine Learning",
    "Analytics",
    "Business Applications",
    "Compute",
    "Databases",
    "Developer Tools",
    "Multicloud",
    "Identity",
    "Integration",
    "Internet of Things",
    "Management and Governance",
    "Media",
    "Migration",
    "Mobile",
    "Networking",
    "Security",
    "Storage",
    "Web",
    "Other",
  ]),
  ServiceName: Schema.String,

  // Recommended fields
  AvailabilityZone: Schema.optional(Schema.NullOr(Schema.String)),
  ChargeFrequency: Schema.optional(Schema.Literals(["One-Time", "Recurring", "Usage-Based"])),

  // Conditional fields
  CommitmentDiscountCategory: Schema.optional(Schema.NullOr(Schema.Literals(["Spend", "Usage"]))),
  CommitmentDiscountId: Schema.optional(Schema.NullOr(Schema.String)),
  CommitmentDiscountName: Schema.optional(Schema.NullOr(Schema.String)),
  CommitmentDiscountStatus: Schema.optional(Schema.NullOr(Schema.Literals(["Used", "Unused"]))),
  CommitmentDiscountType: Schema.optional(Schema.NullOr(Schema.String)),
  ConsumedQuantity: Schema.optional(Schema.NullOr(Schema.Number)),
  ConsumedUnit: Schema.optional(Schema.NullOr(Schema.String)),
  ContractedUnitPrice: Schema.optional(Schema.NullOr(Schema.Number)),
  ListUnitPrice: Schema.optional(Schema.NullOr(Schema.Number)),
  PricingCategory: Schema.optional(Schema.NullOr(Schema.Literals(["Standard", "Dynamic", "Committed", "Other"]))),
  RegionId: Schema.optional(Schema.NullOr(Schema.String)),
  RegionName: Schema.optional(Schema.NullOr(Schema.String)),
  ResourceId: Schema.optional(Schema.NullOr(Schema.String)),
  ResourceName: Schema.optional(Schema.NullOr(Schema.String)),
  ResourceType: Schema.optional(Schema.NullOr(Schema.String)),
  SkuId: Schema.optional(Schema.NullOr(Schema.String)),
  SkuPriceId: Schema.optional(Schema.NullOr(Schema.String)),
  SubAccountId: Schema.optional(Schema.NullOr(Schema.String)),
  SubAccountName: Schema.optional(Schema.NullOr(Schema.String)),
  Tags: Schema.optional(Schema.NullOr(Schema.Record(Schema.String, Schema.String))),
});

export type CostAndUsageRow = typeof CostAndUsageRow.Type;
