import * as Effect from "effect/Effect";
import * as Migrator from "effect/unstable/sql/Migrator";
import { SqlClient } from "effect/unstable/sql/SqlClient";

export const migrations = Migrator.fromRecord({
  "0001_create_focus_datasets": Effect.gen(function* () {
    const sql = yield* SqlClient;
    yield* sql`
      CREATE TABLE IF NOT EXISTS focus_datasets (
        id            TEXT    PRIMARY KEY NOT NULL,
        name          TEXT    NOT NULL,
        focus_version TEXT    NOT NULL,
        dataset_type  TEXT    NOT NULL,
        row_count     INTEGER NOT NULL DEFAULT 0,
        created_at    TEXT    NOT NULL
      )
    `;
  }),
  "0002_create_focus_rows_v10": Effect.gen(function* () {
    const sql = yield* SqlClient;
    yield* sql`
      CREATE TABLE IF NOT EXISTS focus_rows_v10 (
        id                          INTEGER PRIMARY KEY AUTOINCREMENT,
        dataset_id                  TEXT    NOT NULL REFERENCES focus_datasets(id),
        BilledCost                  REAL    NOT NULL,
        BillingAccountId            TEXT    NOT NULL,
        BillingAccountName          TEXT,
        BillingCurrency             TEXT    NOT NULL,
        BillingPeriodEnd            TEXT    NOT NULL,
        BillingPeriodStart          TEXT    NOT NULL,
        ChargeCategory              TEXT    NOT NULL,
        ChargeClass                 TEXT,
        ChargeDescription           TEXT,
        ChargePeriodEnd             TEXT    NOT NULL,
        ChargePeriodStart           TEXT    NOT NULL,
        ContractedCost              REAL    NOT NULL,
        EffectiveCost               REAL    NOT NULL,
        InvoiceIssuerName           TEXT    NOT NULL,
        ListCost                    REAL    NOT NULL,
        PricingQuantity             REAL,
        PricingUnit                 TEXT,
        ProviderName                TEXT    NOT NULL,
        PublisherName               TEXT    NOT NULL,
        ServiceCategory             TEXT    NOT NULL,
        ServiceName                 TEXT    NOT NULL,
        AvailabilityZone            TEXT,
        ChargeFrequency             TEXT,
        CommitmentDiscountCategory  TEXT,
        CommitmentDiscountId        TEXT,
        CommitmentDiscountName      TEXT,
        CommitmentDiscountStatus    TEXT,
        CommitmentDiscountType      TEXT,
        ConsumedQuantity            REAL,
        ConsumedUnit                TEXT,
        ContractedUnitPrice         REAL,
        ListUnitPrice               REAL,
        PricingCategory             TEXT,
        RegionId                    TEXT,
        RegionName                  TEXT,
        ResourceId                  TEXT,
        ResourceName                TEXT,
        ResourceType                TEXT,
        SkuId                       TEXT,
        SkuPriceId                  TEXT,
        SubAccountId                TEXT,
        SubAccountName              TEXT,
        Tags                        TEXT
      )
    `;
  }),
  "0003_create_focus_rows_v11": Effect.gen(function* () {
    const sql = yield* SqlClient;
    yield* sql`
      CREATE TABLE IF NOT EXISTS focus_rows_v11 (
        id                          INTEGER PRIMARY KEY AUTOINCREMENT,
        dataset_id                  TEXT    NOT NULL REFERENCES focus_datasets(id),
        BilledCost                  REAL    NOT NULL,
        BillingAccountId            TEXT    NOT NULL,
        BillingAccountName          TEXT,
        BillingCurrency             TEXT    NOT NULL,
        BillingPeriodEnd            TEXT    NOT NULL,
        BillingPeriodStart          TEXT    NOT NULL,
        ChargeCategory              TEXT    NOT NULL,
        ChargeClass                 TEXT,
        ChargeDescription           TEXT,
        ChargePeriodEnd             TEXT    NOT NULL,
        ChargePeriodStart           TEXT    NOT NULL,
        ContractedCost              REAL    NOT NULL,
        EffectiveCost               REAL    NOT NULL,
        InvoiceIssuerName           TEXT    NOT NULL,
        ListCost                    REAL    NOT NULL,
        PricingQuantity             REAL,
        PricingUnit                 TEXT,
        ProviderName                TEXT    NOT NULL,
        PublisherName               TEXT    NOT NULL,
        ServiceCategory             TEXT    NOT NULL,
        ServiceName                 TEXT    NOT NULL,
        AvailabilityZone            TEXT,
        ChargeFrequency             TEXT,
        ServiceSubcategory          TEXT,
        CapacityReservationId       TEXT,
        CapacityReservationStatus   TEXT,
        CommitmentDiscountCategory  TEXT,
        CommitmentDiscountId        TEXT,
        CommitmentDiscountName      TEXT,
        CommitmentDiscountQuantity  REAL,
        CommitmentDiscountStatus    TEXT,
        CommitmentDiscountType      TEXT,
        CommitmentDiscountUnit      TEXT,
        ConsumedQuantity            REAL,
        ConsumedUnit                TEXT,
        ContractedUnitPrice         REAL,
        ListUnitPrice               REAL,
        PricingCategory             TEXT,
        RegionId                    TEXT,
        RegionName                  TEXT,
        ResourceId                  TEXT,
        ResourceName                TEXT,
        ResourceType                TEXT,
        SkuId                       TEXT,
        SkuMeter                    TEXT,
        SkuPriceDetails             TEXT,
        SkuPriceId                  TEXT,
        SubAccountId                TEXT,
        SubAccountName              TEXT,
        Tags                        TEXT
      )
    `;
  }),
  "0004_create_focus_rows_v12": Effect.gen(function* () {
    const sql = yield* SqlClient;
    yield* sql`
      CREATE TABLE IF NOT EXISTS focus_rows_v12 (
        id                                  INTEGER PRIMARY KEY AUTOINCREMENT,
        dataset_id                          TEXT    NOT NULL REFERENCES focus_datasets(id),
        BilledCost                          REAL    NOT NULL,
        BillingAccountId                    TEXT    NOT NULL,
        BillingAccountName                  TEXT,
        BillingCurrency                     TEXT    NOT NULL,
        BillingPeriodEnd                    TEXT    NOT NULL,
        BillingPeriodStart                  TEXT    NOT NULL,
        ChargeCategory                      TEXT    NOT NULL,
        ChargeClass                         TEXT,
        ChargeDescription                   TEXT,
        ChargePeriodEnd                     TEXT    NOT NULL,
        ChargePeriodStart                   TEXT    NOT NULL,
        ContractedCost                      REAL    NOT NULL,
        EffectiveCost                       REAL    NOT NULL,
        InvoiceIssuerName                   TEXT    NOT NULL,
        ListCost                            REAL    NOT NULL,
        PricingQuantity                     REAL,
        PricingUnit                         TEXT,
        ProviderName                        TEXT    NOT NULL,
        PublisherName                       TEXT    NOT NULL,
        ServiceCategory                     TEXT    NOT NULL,
        ServiceName                         TEXT    NOT NULL,
        AvailabilityZone                    TEXT,
        ChargeFrequency                     TEXT,
        InvoiceId                           TEXT,
        ServiceSubcategory                  TEXT,
        BillingAccountType                  TEXT,
        CapacityReservationId               TEXT,
        CapacityReservationStatus           TEXT,
        CommitmentDiscountCategory          TEXT,
        CommitmentDiscountId                TEXT,
        CommitmentDiscountName              TEXT,
        CommitmentDiscountQuantity          REAL,
        CommitmentDiscountStatus            TEXT,
        CommitmentDiscountType              TEXT,
        CommitmentDiscountUnit              TEXT,
        ConsumedQuantity                    REAL,
        ConsumedUnit                        TEXT,
        ContractedUnitPrice                 REAL,
        ListUnitPrice                       REAL,
        PricingCategory                     TEXT,
        PricingCurrency                     TEXT,
        PricingCurrencyContractedUnitPrice  REAL,
        PricingCurrencyEffectiveCost        REAL,
        PricingCurrencyListUnitPrice        REAL,
        RegionId                            TEXT,
        RegionName                          TEXT,
        ResourceId                          TEXT,
        ResourceName                        TEXT,
        ResourceType                        TEXT,
        SkuId                               TEXT,
        SkuMeter                            TEXT,
        SkuPriceDetails                     TEXT,
        SkuPriceId                          TEXT,
        SubAccountId                        TEXT,
        SubAccountName                      TEXT,
        SubAccountType                      TEXT,
        Tags                                TEXT
      )
    `;
  }),
  "0005_create_focus_rows_v13": Effect.gen(function* () {
    const sql = yield* SqlClient;
    yield* sql`
      CREATE TABLE IF NOT EXISTS focus_rows_v13 (
        id                                  INTEGER PRIMARY KEY AUTOINCREMENT,
        dataset_id                          TEXT    NOT NULL REFERENCES focus_datasets(id),
        BilledCost                          REAL    NOT NULL,
        BillingAccountId                    TEXT    NOT NULL,
        BillingAccountName                  TEXT,
        BillingCurrency                     TEXT    NOT NULL,
        BillingPeriodEnd                    TEXT    NOT NULL,
        BillingPeriodStart                  TEXT    NOT NULL,
        ChargeCategory                      TEXT    NOT NULL,
        ChargeClass                         TEXT,
        ChargeDescription                   TEXT,
        ChargePeriodEnd                     TEXT    NOT NULL,
        ChargePeriodStart                   TEXT    NOT NULL,
        ContractedCost                      REAL    NOT NULL,
        EffectiveCost                       REAL    NOT NULL,
        HostProviderName                    TEXT,
        InvoiceIssuerName                   TEXT    NOT NULL,
        ListCost                            REAL    NOT NULL,
        PricingQuantity                     REAL,
        PricingUnit                         TEXT,
        ServiceCategory                     TEXT    NOT NULL,
        ServiceName                         TEXT    NOT NULL,
        ServiceProviderName                 TEXT    NOT NULL,
        AvailabilityZone                    TEXT,
        ChargeFrequency                     TEXT,
        InvoiceId                           TEXT,
        ServiceSubcategory                  TEXT,
        AllocatedMethodDetails              TEXT,
        AllocatedMethodId                   TEXT,
        AllocatedResourceId                 TEXT,
        AllocatedResourceName               TEXT,
        AllocatedTags                       TEXT,
        BillingAccountType                  TEXT,
        CapacityReservationId               TEXT,
        CapacityReservationStatus           TEXT,
        CommitmentDiscountCategory          TEXT,
        CommitmentDiscountId                TEXT,
        CommitmentDiscountName              TEXT,
        CommitmentDiscountQuantity          REAL,
        CommitmentDiscountStatus            TEXT,
        CommitmentDiscountType              TEXT,
        CommitmentDiscountUnit              TEXT,
        ConsumedQuantity                    REAL,
        ConsumedUnit                        TEXT,
        ContractApplied                     TEXT,
        ContractedUnitPrice                 REAL,
        ListUnitPrice                       REAL,
        PricingCategory                     TEXT,
        PricingCurrency                     TEXT,
        PricingCurrencyContractedUnitPrice  REAL,
        PricingCurrencyEffectiveCost        REAL,
        PricingCurrencyListUnitPrice        REAL,
        RegionId                            TEXT,
        RegionName                          TEXT,
        ResourceId                          TEXT,
        ResourceName                        TEXT,
        ResourceType                        TEXT,
        SkuId                               TEXT,
        SkuMeter                            TEXT,
        SkuPriceDetails                     TEXT,
        SkuPriceId                          TEXT,
        SubAccountId                        TEXT,
        SubAccountName                      TEXT,
        SubAccountType                      TEXT,
        Tags                                TEXT,
        ProviderName                        TEXT,
        PublisherName                       TEXT
      )
    `;
  }),
  "0006_create_focus_rows_v13_contract_commitment": Effect.gen(function* () {
    const sql = yield* SqlClient;
    yield* sql`
      CREATE TABLE IF NOT EXISTS focus_rows_v13_contract_commitment (
        id                                INTEGER PRIMARY KEY AUTOINCREMENT,
        dataset_id                        TEXT    NOT NULL REFERENCES focus_datasets(id),
        BillingCurrency                   TEXT,
        ContractCommitmentCategory        TEXT    NOT NULL,
        ContractCommitmentCost            REAL,
        ContractCommitmentDescription     TEXT,
        ContractCommitmentId              TEXT,
        ContractCommitmentPeriodEnd       TEXT    NOT NULL,
        ContractCommitmentPeriodStart     TEXT    NOT NULL,
        ContractCommitmentQuantity        REAL,
        ContractCommitmentType            TEXT    NOT NULL,
        ContractCommitmentUnit            TEXT,
        ContractId                        TEXT,
        ContractPeriodEnd                 TEXT    NOT NULL,
        ContractPeriodStart               TEXT    NOT NULL
      )
    `;
  }),
});
